import { NextRequest, NextResponse } from 'next/server';
import { readFileSync, existsSync } from 'fs';
import path from 'path';

/**
 * GET /api/questions/[roundId]
 *
 * Serves the challenge question JSON for a given round.
 * Questions are generated by the oracle scripts and stored at:
 *   ~/scripts/mine/questions/round-{N}.json
 *
 * Returns:
 *   200 + question JSON (without answer)
 *   404 if round not found or not yet posted
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ roundId: string }> }
) {
  const { roundId } = await params;
  const id = parseInt(roundId, 10);

  if (isNaN(id) || id < 1 || id > 140) {
    return NextResponse.json(
      { error: 'Invalid roundId — must be 1–140' },
      { status: 400 }
    );
  }

  // Path matches oracle config: ~/scripts/mine/questions/round-{N}.json
  const questionsDir = path.join(process.env.HOME || '/Users/clawcustos', 'scripts', 'mine', 'questions');
  const filePath = path.join(questionsDir, `round-${id}.json`);

  if (!existsSync(filePath)) {
    return NextResponse.json(
      { error: `Round ${id} not found. Question not yet posted by oracle.` },
      { status: 404 }
    );
  }

  try {
    const raw = readFileSync(filePath, 'utf8');
    const data = JSON.parse(raw);

    // Strip answer fields — only serve the public question
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { answer, answerHash, ...publicData } = data;

    return NextResponse.json(publicData, {
      headers: {
        'Cache-Control': 'public, max-age=60, stale-while-revalidate=300',
      },
    });
  } catch (err) {
    console.error(`[questions API] Failed to read round ${id}:`, err);
    return NextResponse.json(
      { error: 'Internal error reading question file' },
      { status: 500 }
    );
  }
}
